blueprint:
  name: Manual Light Override Flag (with Timer)
  description: >
    When you manually adjust a light's brightness via UI (not by automation),
    set a helper boolean to "on" and start a timer. When the timer expires,
    clear the override flag. This survives Home Assistant restarts.
  domain: automation

  input:
    light:
      name: Light
      description: The light entity to monitor for manual brightness changes
      selector:
        entity:
          domain: light

    override_flag:
      name: Override Flag
      description: The input_boolean helper to turn on/off
      selector:
        entity:
          domain: input_boolean

    override_timer:
      name: Override Timer
      description: The timer helper that controls when to clear the flag
      selector:
        entity:
          domain: timer

trigger:
  # Trigger 1: Manual brightness adjustment
  - platform: state
    entity_id: !input light
    attribute: brightness
    id: manual_adjust
  
  # Trigger 2: Timer finished
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input override_timer
    id: timer_finished

condition: []

action:
  - choose:
      # Manual adjustment detected
      - conditions:
          - condition: trigger
            id: manual_adjust
          - condition: template
            value_template: "{{ trigger.to_state.context.id != none }}"
          - condition: template
            value_template: "{{ trigger.to_state.context.parent_id == none }}"
        sequence:
          # Turn on the override flag
          - service: input_boolean.turn_on
            target:
              entity_id: !input override_flag
          
          # Start the timer
          - service: timer.start
            target:
              entity_id: !input override_timer
      
      # Timer finished
      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          # Turn off the override flag
          - service: input_boolean.turn_off
            target:
              entity_id: !input override_flag

mode: single
